version: "3.8"
services:
  web:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/todo
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - ./:/var/lib/postgresql/data