"""empty message

Revision ID: 820782433f21
Revises: 6f69f4883ced
Create Date: 2022-03-25 15:00:28.533104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820782433f21'
down_revision = '6f69f4883ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
